data:
  url: "https://raw.githubusercontent.com/karpathy/ng-video-lecture/master/input.txt"
  batch_size: 64
  max_length: 128
  num_workers: 4

tokenizer:
  file_path: "utils/tokenizer.json"

model:
  num_tokens: 100
  d_model: 256
  n_layers: 3
  expansion: 2 # 2 in original paper, multiplicator of d_model
  d_hidden: 2 # 16 in original paper, multiplicator of d_model
  dt_min: 0.001 # default from the original paper
  dt_max: 0.1 # default from the original paper
  kernel_size: 5 # must be odd

train:
  epochs: 20
  lr: 0.00001
  factor: 0.5
  patience: 5
  log_interval: 100
  save_interval: 1000
  save_dir: "checkpoints/run2"
  resume_path: None
