data:
  url: "https://raw.githubusercontent.com/karpathy/ng-video-lecture/master/input.txt"
  batch_size: 64
  max_length: 256
  num_workers: 4

tokenizer:
  file_path: "utils/tokenizer.json"

model:
  num_tokens: 10000
  d_model: 128
  n_layers: 3
  expansion: 2
  d_hidden: 2
  dt_min: 0.001
  dt_max: 0.1
  kernel_size: 5

train:
  epochs: 20
  lr: 0.00001
  factor: 0.5
  patience: 2
  log_interval: 100
  save_dir: "checkpoints/run1"
  resume_path: None
